MvcBlog/Controllers/AboutController.cs
using Business.Concrete;
using DataAccess.Ef;
using DataAccessLayer.EntityFramework;
using Entity.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcBlog.Controllers
{
    [AllowAnonymous]
    public class AboutController : Controller
    {
       
        // GET: About
        AboutManager abm = new AboutManager(new EfAboutDal());
        public ActionResult Index()
        {
            var aboutcontent = abm.GetList();
            return View(aboutcontent);
        }
        public PartialViewResult Footer()
        {
            var aboutContentlist=abm.GetList();
            return PartialView(aboutContentlist);
        }
        public PartialViewResult MeetTheTeam()
        {
            AuthorManager auth = new AuthorManager(new EfAuthorDal());
            var outhorlist = auth.GetList();
            return PartialView(outhorlist);
        }
        [HttpGet]
       public ActionResult UpdateAbout()
        {
            var aboutlsit = abm.GetList(); 
            return View(aboutlsit);
        }
        [HttpPost]
        public ActionResult UpdateAbout(About a)
        {
            abm.TUpdate(a);
            return RedirectToAction("UpdateAbout");
        }
    }
}

MvcBlog/Controllers/ContactController.cs
using Business.Concrete;
using DataAccessLayer.EntityFramework;
using Entity.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcBlog.Controllers
{
    public class ContactController : Controller
    {
        // GET: Contact
        ContactManager cm = new ContactManager(new EfContactDal());
        [AllowAnonymous]
        public ActionResult Index()
        {
            return View();
        }
        [AllowAnonymous]
        public ActionResult SendMessage()
        {
            return View();
        }
        [HttpPost]
        public ActionResult SendMessage(Contact x)
        {
            cm.TAdd(x);
            return View();
        }
        public ActionResult SendBox()
        {
            var contactlist = cm.GetList();
            return View(contactlist);
        }
        public ActionResult MessageDetails(int id)
        {
            Contact contact = cm.GetByID(id);
            return View(contact);
        }
    }
}

MvcBlog/Views/Shared/Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Mini Blog</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Muli:300,400,700|Playfair+Display:400,700,900" rel="stylesheet">

    <link rel="stylesheet" href="~/miniblog/fonts/icomoon/style.css">
    <link rel="stylesheet" href="~/miniblog/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/miniblog/css/magnific-popup.css">
    <link rel="stylesheet" href="~/miniblog/css/jquery-ui.css">
    <link rel="stylesheet" href="~/miniblog/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/miniblog/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="~/miniblog/css/bootstrap-datepicker.css">
    <link rel="stylesheet" href="~/miniblog/fonts/flaticon/font/flaticon.css">
    <link rel="stylesheet" href="~/miniblog/css/aos.css">

    <link rel="stylesheet" href="~/miniblog/css/style.css">
</head>
<body>

    <div class="site-wrap">

        <div class="site-mobile-menu">
            <div class="site-mobile-menu-header">
                <div class="site-mobile-menu-close mt-3">
                    <span class="icon-close2 js-menu-toggle"></span>
                </div>
            </div>
            <div class="site-mobile-menu-body"></div>
        </div>

        <header class="site-navbar" role="banner">
            <div class="container-fluid">
                <div class="row align-items-center">

                    <div class="col-12 search-form-wrap js-search-form">
                        <form method="get" action="#">
                            <input type="text" id="s" class="form-control" placeholder="Search...">
                            <button class="search-btn" type="submit"><span class="icon-search"></span></button>
                        </form>
                    </div>

                    <div class="col-4 site-logo">
                        <a href="/Blog/Index/" class="text-black h2 mb-0">Mini Blog</a>
                    </div>

                    <div class="col-8 text-right">
                        <nav class="site-navigation" role="navigation">
                            <ul class="site-menu js-clone-nav mr-auto d-none d-lg-block mb-0">
                                <li><a href="/Blog/Index/">Anasayfa</a></li>
                                <li><a href="/Blog/BlogByCategory/1/">Yazılım</a></li>
                                <li><a href="/Blog/BlogByCategory/2/">Teknoloji</a></li>
                                <li><a href="/Blog/BlogByCategory/4/">Kültür Sanat</a></li>
                                <li><a href="/Blog/BlogByCategory/7/">Seyehat</a></li>
                                <li><a href="/Blog/BlogByCategory/3/">Spor</a></li>
                                <li><a href="/About/Index/">Hakkımızda</a></li>
                                <li><a href="/Contact/SendMessage/">İletişim</a></li>
                                <li class="d-none d-lg-inline-block"><a href="#" class="js-search-toggle"><span class="icon-search"></span></a></li>
                            </ul>
                        </nav>
                        <a href="#" class="site-menu-toggle js-menu-toggle text-black d-inline-block d-lg-none"><span class="icon-menu h3"></span></a>
                    </div>
                </div>

            </div>
        </header>


        
        @RenderBody()
        

 
      

    <script src="~/miniblog/js/jquery-3.3.1.min.js"></script>
    <script src="~/miniblog/js/jquery-migrate-3.0.1.min.js"></script>
    <script src="~/miniblog/js/jquery-ui.js"></script>
    <script src="~/miniblog/js/popper.min.js"></script>
    <script src="~/miniblog/js/bootstrap.min.js"></script>
    <script src="~/miniblog/js/owl.carousel.min.js"></script>
    <script src="~/miniblog/js/jquery.stellar.min.js"></script>
    <script src="~/miniblog/js/jquery.countdown.min.js"></script>
    <script src="~/miniblog/js/jquery.magnific-popup.min.js"></script>
    <script src="~/miniblog/js/bootstrap-datepicker.min.js"></script>
    <script src="~/miniblog/js/aos.js"></script>

    <script src="~/miniblog/js/main.js"></script>


</body>
</html>

MvcBlog/Views/Shared/_AdminLayout.cshtml
                       
                      
                     
         

@{
    Layout = null;
}
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>INSPINIA | Lightbox Gallery</title>

    <link href="~/inspiniaTema/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/inspiniaTema/font-awesome/css/font-awesome.css" rel="stylesheet">
    <link href="~/inspiniaTema/css/plugins/blueimp/css/blueimp-gallery.min.css" rel="stylesheet">
    <link href="~/inspiniaTema/css/animate.css" rel="stylesheet">
    <link href="~/inspiniaTema/css/style.css" rel="stylesheet">

</head>

<body>

    <div id="wrapper">

        <nav class="navbar-default navbar-static-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav metismenu" id="side-menu">
                    <li class="nav-header">
                        <div class="dropdown profile-element">
                            <img alt="image" class="rounded-circle" src="~/inspiniaTema/img/profile_small.jpg" />
                            <a data-toggle="dropdown" class="dropdown-toggle" href="#">

                            </a>
                            <ul class="dropdown-menu animated fadeInRight m-t-xs">
                                <li><a class="dropdown-item" href="profile.html">Profile</a></li>
                                <li><a class="dropdown-item" href="contacts.html">Contacts</a></li>
                                <li><a class="dropdown-item" href="mailbox.html">Mailbox</a></li>
                                <li class="dropdown-divider"></li>
                                <li><a class="dropdown-item" href="login.html">Çıkış Yap</a></li>
                            </ul>
                        </div>
                        <div class="logo-element">
                            IN+
                        </div>
                    </li>
                    <li>

                        <a href="index.html"><i class="fa fa-th-large"></i> <span class="nav-label">İşlemler</span> <span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level collapse">

                            <li><a href="/Blog/AdminBlogList">Bloglar</a></li>
                            <li><a href="/Category/AdminCategoryList">Kategoriler</a></li>
                            <li><a href="/Author/AuthorList">Yazarlar</a></li>
                            
                        </ul>
                    </li>
                    <li>

                        <a href="index.html"><i class="fa fa-th-large"></i> <span class="nav-label">Yorumlar</span> <span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level collapse">

                            <li><a href="/Comment/AdminCommentList">Yayınlanan Yorumlar</a></li>
                            <li><a href="/Comment/AdminCommentListFalse/">Kaldırılan Yorumlar</a></li>
                        </ul>
                    </li>

                    <li>
                        <a href="/About/UpdateAbout"><i class="fa fa-pie-chart"></i> <span class="nav-label">Hakkımızda</span>  </a>
                    </li>
                    <li>
                        <a href="/Contact/SendBox"><i class="fa fa-flask"></i> <span class="nav-label">İletişim-Mesaj</span></a>
                    </li>
                    <li>
                        <a href="/User/LogOut"><i class="fa fa-laptop"></i> <span class="nav-label">Çıkış Yap</span></a>
                    </li>



                </ul>

            </div>
        </nav>

        <div id="page-wrapper" class="gray-bg">
            <div class="row border-bottom">
                <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
                    <div class="navbar-header">
                        <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
                        <form role="search" class="navbar-form-custom" action="search_results.html">
                            <div class="form-group">
                                <input type="text" placeholder="Search for something..." class="form-control" name="top-search" id="top-search">
                            </div>
                        </form>
                    </div>
                    <ul class="nav navbar-top-links navbar-right">
                        <li>
                            <span class="m-r-sm text-muted welcome-message">Welcome to INSPINIA+ Admin Theme.</span>
                        </li>
                        <li class="dropdown">
                            <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
                                <i class="fa fa-envelope"></i>  <span class="label label-warning">16</span>
                            </a>
                            <ul class="dropdown-menu dropdown-messages">
                                <li>
                                    <div class="dropdown-messages-box">
                                        <a class="dropdown-item float-left" href="profile.html">
                                            <img alt="image" class="rounded-circle" src="img/a7.jpg">
                                        </a>
                                        <div class="media-body">
                                            <small class="float-right">46h ago</small>
                                            <strong>Mike Loreipsum</strong> started following <strong>Monica Smith</strong>. <br>
                                            <small class="text-muted">3 days ago at 7:58 pm - 10.06.2014</small>
                                        </div>
                                    </div>
                                </li>
                                <li class="dropdown-divider"></li>
                                <li>
                                    <div class="dropdown-messages-box">
                                        <a class="dropdown-item float-left" href="profile.html">
                                            <img alt="image" class="rounded-circle" src="img/a4.jpg">
                                        </a>
                                        <div class="media-body ">
                                            <small class="float-right text-navy">5h ago</small>
                                            <strong>Chris Johnatan Overtunk</strong> started following <strong>Monica Smith</strong>. <br>
                                            <small class="text-muted">Yesterday 1:21 pm - 11.06.2014</small>
                                        </div>
                                    </div>
                                </li>
                                <li class="dropdown-divider"></li>
                                <li>
                                    <div class="dropdown-messages-box">
                                        <a class="dropdown-item float-left" href="profile.html">
                                            <img alt="image" class="rounded-circle" src="img/profile.jpg">
                                        </a>
                                        <div class="media-body ">
                                            <small class="float-right">23h ago</small>
                                            <strong>Monica Smith</strong> love <strong>Kim Smith</strong>. <br>
                                            <small class="text-muted">2 days ago at 2:30 am - 11.06.2014</small>
                                        </div>
                                    </div>
                                </li>
                                <li class="dropdown-divider"></li>
                                <li>
                                    <div class="text-center link-block">
                                        <a href="mailbox.html" class="dropdown-item">
                                            <i class="fa fa-envelope"></i> <strong>Read All Messages</strong>
                                        </a>
                                    </div>
                                </li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
                                <i class="fa fa-bell"></i>  <span class="label label-primary">8</span>
                            </a>
                            <ul class="dropdown-menu dropdown-alerts">
                                <li>
                                    <a href="mailbox.html" class="dropdown-item">
                                        <div>
                                            <i class="fa fa-envelope fa-fw"></i> You have 16 messages
                                            <span class="float-right text-muted small">4 minutes ago</span>
                                        </div>
                                    </a>
                                </li>
                                <li class="dropdown-divider"></li>
                                <li>
                                    <a href="profile.html" class="dropdown-item">
                                        <div>
                                            <i class="fa fa-twitter fa-fw"></i> 3 New Followers
                                            <span class="float-right text-muted small">12 minutes ago</span>
                                        </div>
                                    </a>
                                </li>
                                <li class="dropdown-divider"></li>
                                <li>
                                    <a href="grid_options.html" class="dropdown-item">
                                        <div>
                                            <i class="fa fa-upload fa-fw"></i> Server Rebooted
                                            <span class="float-right text-muted small">4 minutes ago</span>
                                        </div>
                                    </a>
                                </li>
                                <li class="dropdown-divider"></li>
                                <li>
                                    <div class="text-center link-block">
                                        <a href="notifications.html" class="dropdown-item">
                                            <strong>See All Alerts</strong>
                                            <i class="fa fa-angle-right"></i>
                                        </a>
                                    </div>
                                </li>
                            </ul>
                        </li>


                        <li>
                            <a href="login.html">
                                <i class="fa fa-sign-out"></i> Log out
                            </a>
                        </li>
                    </ul>

                </nav>
            </div>
            <div class="row wrapper border-bottom white-bg page-heading">

                <div class="col-lg-2">

                </div>
            </div>
            <div class="wrapper wrapper-content">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="ibox ">

                            <div class="ibox-content">
                                @RenderBody()



                            </div>
                        </div>
                    </div>

                </div>
            </div>


        </div>
    </div>



    <!-- Mainly scripts -->
    <script src="~/inspiniaTema/js/jquery-3.1.1.min.js"></script>
    <script src="~/inspiniaTema/js/popper.min.js"></script>
    <script src="~/inspiniaTema/js/bootstrap.js"></script>
    <script src="~/inspiniaTema/js/plugins/metisMenu/jquery.metisMenu.js"></script>
    <script src="~/inspiniaTema/js/plugins/slimscroll/jquery.slimscroll.min.js"></script>

    <!-- Custom and plugin javascript -->
    <script src="~/inspiniaTema/js/inspinia.js"></script>
    <script src="~/inspiniaTema/js/plugins/pace/pace.min.js"></script>

    <!-- blueimp gallery -->
    <script src="~/inspiniaTema/js/plugins/blueimp/jquery.blueimp-gallery.min.js"></script>

</body>

</html>

MvcBlog/Views/Shared/_AuthorLayout.cshtml
@{

    Layout = null;

}

<!DOCTYPE html>

<html>

<head>

    <meta charset="utf-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>AdminLTE 3 | Admin</title>

    <!-- Tell the browser to be responsive to screen width -->

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Font Awesome -->

    <link rel="stylesheet" href="~/AdminLTE-3.0.4/plugins/fontawesome-free/css/all.min.css">

    <!-- Ionicons -->

    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">

    <!-- overlayScrollbars -->

    <link rel="stylesheet" href="~/AdminLTE-3.0.4/dist/css/adminlte.min.css">

    <!-- Google Font: Source Sans Pro -->

    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

</head>

<body class="hold-transition sidebar-mini">

    <!-- Site wrapper -->

    <div class="wrapper">

        <!-- Navbar -->
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->

        <aside class="main-sidebar sidebar-dark-primary elevation-4">

            <!-- Brand Logo -->

            <a href="../../index3.html" class="brand-link">

                <img src="~/AdminLTE-3.0.4/dist/img/AdminLTELogo.png"
                     alt="AdminLTE Logo"
                     class="brand-image img-circle elevation-3"
                     style="opacity: .8">

                <span class="brand-text font-weight-light">Blog Sistemi</span>

            </a>

            <!-- Sidebar -->

            <div class="sidebar">

                <!-- Sidebar user (optional) -->

                <div class="user-panel mt-3 pb-3 mb-3 d-flex">

                    <div class="image">

                        <img src="~/AdminLTE-3.0.4/dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">

                    </div>

                    <div class="info">

                        <a href="#" class="d-block">Ad Soyad</a>

                    </div>

                </div>

                <!-- Sidebar Menu -->

                <nav class="mt-2">

                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">

                        <!-- Add icons to the links using the .nav-icon class

    with font-awesome or any other icon font library -->



                        <li class="nav-item">

                            <a href="/User/BlogList/" class="nav-link">

                                <i class="nav-icon fas fa-th"></i>

                                <p>
                                    Bloglarım
                                </p>

                            </a>

                        </li>


                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-comment"></i>
                                <p>
                                    Yorumlar
                                    <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a href="/Comment/AdminCommentList/" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Yayınlanan Yorumlar</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="/Comment/UpdateCommentToFalse/" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Kaldırılan Yorumlar</p>
                                    </a>
                                </li>

                            </ul>
                        </li>
                        <li class="nav-item">

                            <a href="../widgets.html" class="nav-link">

                                <i class="nav-icon fas fa-address-card"></i>

                                <p>
                                    Profilim
                                </p>

                            </a>

                        </li>
                        <li class="nav-item">

                            <a href="/User/LogOut/" class="nav-link">

                                <i class="nav-icon fas fa-car"></i>

                                <p>
                                    Çıkış Yap
                                </p>

                            </a>

                        </li>
                    </ul>

                </nav>

                <!-- /.sidebar-menu -->

            </div>

            <!-- /.sidebar -->

        </aside>

        <!-- Content Wrapper. Contains page content -->

        <div class="content-wrapper">

            <!-- Content Header (Page header) -->

            <section class="content-header">

                <div class="container-fluid">

                    @RenderBody()


                </div><!-- /.container-fluid -->

            </section>

            <!-- Main content -->
            <!-- /.content -->

        </div>

        <!-- /.content-wrapper -->
        <!-- Control Sidebar -->

        <aside class="control-sidebar control-sidebar-dark">

            <!-- Control sidebar content goes here -->

        </aside>

        <!-- /.control-sidebar -->

    </div>

    <!-- ./wrapper -->
    <!-- jQuery -->

    <script src="~/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>

    <!-- Bootstrap 4 -->

    <script src="~/AdminLTE-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- AdminLTE App -->

    <script src="~/AdminLTE-3.0.4/dist/js/adminlte.min.js"></script>

    <!-- AdminLTE for demo purposes -->

    <script src="~/AdminLTE-3.0.4/dist/js/demo.js"></script>

</body>

</html>

MvcBlog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - ASP.NET Uygulamam</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Uygulama adı", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Giriş Sayfası", "Index", "Home")</li>
                    <li>@Html.ActionLink("Hakkında", "About", "Home")</li>
                    <li>@Html.ActionLink("Kişi", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - ASP.NET Uygulamam</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>