MvcBlog/Controllers/AboutController.cs
using Business.Concrete;
using DataAccess.Ef;
using DataAccessLayer.EntityFramework;
using Entity.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcBlog.Controllers
{
    [AllowAnonymous]
    public class AboutController : Controller
    {
       
        // GET: About
        AboutManager abm = new AboutManager(new EfAboutDal());
        public ActionResult Index()
        {
            var aboutcontent = abm.GetList();
            return View(aboutcontent);
        }
        public PartialViewResult Footer()
        {
            var aboutContentlist=abm.GetList();
            return PartialView(aboutContentlist);
        }
        public PartialViewResult MeetTheTeam()
        {
            AuthorManager auth = new AuthorManager(new EfAuthorDal());
            var outhorlist = auth.GetList();
            return PartialView(outhorlist);
        }
        [HttpGet]
       public ActionResult UpdateAbout()
        {
            var aboutlsit = abm.GetList(); 
            return View(aboutlsit);
        }
        [HttpPost]
        public ActionResult UpdateAbout(About a)
        {
            abm.TUpdate(a);
            return RedirectToAction("UpdateAbout");
        }
    }
}

MvcBlog/Controllers/AuthorController.cs
using Business.Concrete;
using Business.ValidationRules;
using DataAccess.Ef;
using Entity.Concrete;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcBlog.Controllers
{
    public class AuthorController : Controller
    {
        // GET: Author
        BlogManager bm = new BlogManager(new EfBlogDal());
        AuthorManager amn = new AuthorManager(new EfAuthorDal());

        [AllowAnonymous]
        public PartialViewResult AuthorAbout(int id)
        {
            var authordetail = bm.GetByID(id);
            return PartialView(authordetail);
        }
        [AllowAnonymous]
        public PartialViewResult AuthorPopularPost(int id)
        {
            var blogauthorId = bm.GetList().Where(x => x.BlogId == id).Select(y=>y.AuthorId).FirstOrDefault();
         
            var authorblogs = bm.GetBlogByAuthor(blogauthorId);
            return PartialView(authorblogs);
        }
        public ActionResult AuthorList()
        {
            var list = amn.GetList();
            return View(list);
        }
        public ActionResult AddAuthor()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddAuthor(Author a)
        {
            AuthorValidator authorvalidator = new AuthorValidator();
            ValidationResult result = authorvalidator.Validate(a);
            if (result.IsValid)
            {
                amn.TAdd(a);
                return RedirectToAction("AuthorList");
            }
            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }
        [HttpGet]
        public ActionResult UpdateAuthor(int id)
        {
            Author author = amn.GetByID(id);
            return View(author);
        }
        [HttpPost]
        public ActionResult UpdateAuthor(Author a)
        {
            AuthorValidator authorvalidator = new AuthorValidator();
            ValidationResult result = authorvalidator.Validate(a);
            if (result.IsValid)
            {
                amn.TUpdate(a);
                return RedirectToAction("AuthorList");
            }
            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
           
        }
    }
}

MvcBlog/Controllers/BlogController.cs
using Business.Concrete;
using DataAccess.Concrete;
using DataAccess.Ef;
using DataAccessLayer.EntityFramework;
using Entity.Concrete;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcBlog.Controllers
{
    public class BlogController : Controller
    {
        // GET: Blog
        BlogManager bm = new BlogManager(new EfBlogDal());
        CommentManager cm = new CommentManager(new EfCommentDal());

        [AllowAnonymous]
        public ActionResult Index()
        {
            return View();
        }
        [AllowAnonymous]
        public PartialViewResult BlogList(int page = 1)
        {
            var list = bm.GetList().ToPagedList(page, 3);
            return PartialView(list);
        }
        [AllowAnonymous]
        public PartialViewResult FeaturedPost()
        {
            //1.post
            var posttitle1 = bm.GetList().OrderByDescending(z => z.BlogId).Where(x => x.CategoryId == 1).Select(y => y.BlogTitle).FirstOrDefault();
            var postimage1 = bm.GetList().OrderByDescending(z => z.BlogId).Where(x => x.CategoryId == 1).Select(y => y.BlogImage).FirstOrDefault();
            var postblogdate1 = bm.GetList().OrderByDescending(z => z.BlogId).Where(x => x.CategoryId == 1).Select(y => y.BlogDate).FirstOrDefault();
            var blogpostid1 = bm.GetList().OrderByDescending(z => z.BlogId).Where(x => x.CategoryId == 1).Select(y => y.BlogId).FirstOrDefault();
            //2.post
            var posttitle2 = bm.GetList().OrderByDescending(z => z.BlogId).Where(x => x.CategoryId == 2).Select(y => y.BlogTitle).FirstOrDefault();
            var postimage2 = bm.GetList().OrderByDescending(z => z.BlogId).Where(x => x.CategoryId == 2).Select(y => y.BlogImage).FirstOrDefault();
            var postblogdate2 = bm.GetList().OrderByDescending(z => z.BlogId).Where(x => x.CategoryId == 2).Select(y => y.BlogDate).FirstOrDefault();
            var blogpostid2 = bm.GetList().OrderByDescending(z => z.BlogId).Where(x => x.CategoryId == 2).Select(y => y.BlogId).FirstOrDefault();
            //3.post
            var posttitle3 = bm.GetList().OrderByDescending(z => z.BlogId).Where(x => x.CategoryId == 3).Select(y => y.BlogTitle).FirstOrDefault();
            var postimage3 = bm.GetList().OrderByDescending(z => z.BlogId).Where(x => x.CategoryId == 3).Select(y => y.BlogImage).FirstOrDefault();
            var postblogdate3 = bm.GetList().OrderByDescending(z => z.BlogId).Where(x => x.CategoryId == 3).Select(y => y.BlogDate).FirstOrDefault();
            var blogpostid3 = bm.GetList().OrderByDescending(z => z.BlogId).Where(x => x.CategoryId == 3).Select(y => y.BlogId).FirstOrDefault();
            //4.post
            var posttitle4 = bm.GetList().OrderByDescending(z => z.BlogId).Where(x => x.CategoryId == 4).Select(y => y.BlogTitle).FirstOrDefault();
            var postimage4 = bm.GetList().OrderByDescending(z => z.BlogId).Where(x => x.CategoryId == 4).Select(y => y.BlogImage).FirstOrDefault();
            var postblogdate4 = bm.GetList().OrderByDescending(z => z.BlogId).Where(x => x.CategoryId == 4).Select(y => y.BlogDate).FirstOrDefault();
            var blogpostid4 = bm.GetList().OrderByDescending(z => z.BlogId).Where(x => x.CategoryId == 4).Select(y => y.BlogId).FirstOrDefault();
            //Öne çıkan post
            var posttitle5 = bm.GetList().OrderByDescending(z => z.BlogId).Where(x => x.CategoryId == 5).Select(y => y.BlogTitle).FirstOrDefault();
            var postimage5 = bm.GetList().OrderByDescending(z => z.BlogId).Where(x => x.CategoryId == 5).Select(y => y.BlogImage).FirstOrDefault();
            var postblogdate5 = bm.GetList().OrderByDescending(z => z.BlogId).Where(x => x.CategoryId == 5).Select(y => y.BlogDate).FirstOrDefault();
            var blogpostid5 = bm.GetList().OrderByDescending(z => z.BlogId).Where(x => x.CategoryId == 5).Select(y => y.BlogId).FirstOrDefault();

            ViewBag.posttitle1 = posttitle1;
            ViewBag.postimage1 = postimage1;
            ViewBag.postblogdate1 = postblogdate1;
            ViewBag.blogpostid1 = blogpostid1;

            ViewBag.posttitle2 = posttitle2;
            ViewBag.postimage2 = postimage2;
            ViewBag.postblogdate2 = postblogdate2;
            ViewBag.blogpostid2 = blogpostid2;

            ViewBag.posttitle3 = posttitle3;
            ViewBag.postimage3 = postimage3;
            ViewBag.postblogdate3 = postblogdate3;
            ViewBag.blogpostid3 = blogpostid3;

            ViewBag.posttitle4 = posttitle4;
            ViewBag.postimage4 = postimage4;
            ViewBag.postblogdate4 = postblogdate4;
            ViewBag.blogpostid4 = blogpostid4;
            ViewBag.posttitle5 = posttitle5;
            ViewBag.postimage5 = postimage5;
            ViewBag.postblogdate5 = postblogdate5;
            ViewBag.blogpostid5 = blogpostid5;

            return PartialView();
        }
        [AllowAnonymous]
        public PartialViewResult OtherFeaturedPost()
        {
            return PartialView();
        }
        [AllowAnonymous]
        public ActionResult BlogDetails()
        {
            return View();
        }
        [AllowAnonymous]
        public PartialViewResult BlogCover(int id)
        {
            var blogdetail = bm.GetBlogByID(id);
            return PartialView(blogdetail);
        }
        [AllowAnonymous]
        public PartialViewResult BlogReadAll(int id)
        {
            var blogdetail = bm.GetBlogByID(id);
            return PartialView(blogdetail);
        }
        public PartialViewResult CommentPartial()
        {
            return PartialView();
        }
        [AllowAnonymous]
        public ActionResult BlogByCategory(int id)
        {
            var bloglistbycatgeory = bm.GetBlogByCategory(id);
            var categoryname = bm.GetBlogByCategory(id).Select(y => y.Category.CategoryName).FirstOrDefault();
            var categorydesc = bm.GetBlogByCategory(id).Select(y => y.Category.CategoryDescription).FirstOrDefault();
            ViewBag.categoryname = categoryname;
            ViewBag.categorydesc = categorydesc;
            return View(bloglistbycatgeory);
        }
        public ActionResult AdminBlogList()
        {
            var bloglist = bm.GetList();
            return View(bloglist);
        }
        public ActionResult AdminBlogList2()
        {
            var bloglist = bm.GetList();
            return View(bloglist);
        }
        [Authorize(Roles = "A")]
        [HttpGet]
        public ActionResult AddNewBlog()
        {
            Context c = new Context();
            List<SelectListItem> values = (from x in c.Categories.ToList() select new SelectListItem { Text = x.CategoryName, Value = x.CategoryId.ToString() }).ToList();
            List<SelectListItem> values2 = (from x in c.Authors.ToList() select new SelectListItem { Text = x.AuthorName, Value = x.AuthorId.ToString() }).ToList();
            ViewBag.author = values2;
            ViewBag.category = values;
            return View();
        }
        [HttpPost]
        public ActionResult AddNewBlog(Blog b)
        {
            bm.TAdd(b);
            return RedirectToAction("AdminBlogList");
        }
        public ActionResult DeleteBlog(Blog id)
        {
            bm.TDelete(id);
            return RedirectToAction("AdminBlogList");
        }
        public ActionResult UpdateBlog(int id)
        {
            Context c = new Context();
            List<SelectListItem> values = (from x in c.Categories.ToList() select new SelectListItem { Text = x.CategoryName, Value = x.CategoryId.ToString() }).ToList();
            List<SelectListItem> values2 = (from x in c.Authors.ToList() select new SelectListItem { Text = x.AuthorName, Value = x.AuthorId.ToString() }).ToList();
            ViewBag.author = values2;
            ViewBag.category = values;
            Blog blog = bm.GetByID(id);
            return View(blog);
        }
        [HttpPost]
        public ActionResult UpdateBlog(Blog p)
        {
            bm.TUpdate(p);
            return RedirectToAction("AdminBlogList");
        }
        public ActionResult GetCommentByBlog(int id)
        {
           
            var commentlist = cm.CommentByBlog(id);
            return View(commentlist);
        }
        public ActionResult AuthorBlogList(int id)
        {
            var blogs = bm.GetBlogByAuthor(id);
            return View(blogs);
        }
     
    }
}

MvcBlog/Controllers/CategoryController.cs
using Business.Concrete;
using Business.ValidationRules;
using DataAccess.Ef;
using DataAccess.Interface;
using Entity.Concrete;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcBlog.Controllers
{
    public class CategoryController : Controller
    {
       CategoryManager cm = new CategoryManager(new EfCategoryDal());
        public ActionResult Index()
        {
            var categories = cm.GetList();
            return View(categories);
        }
        [AllowAnonymous]
        public PartialViewResult CategoryList()
        {
            var categories = cm.GetList();
            return PartialView(categories);
        }
        public ActionResult AdminCategoryList()
        {
            var categories = cm.GetList();
            return View(categories);
        }
        [HttpGet]
        public ActionResult AdminCategoryAdd()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AdminCategoryAdd(Category ca)
        {
            CategoryValidator categoryvalidator = new CategoryValidator();
            ValidationResult result = categoryvalidator.Validate(ca);
            if (result.IsValid)
            {
                cm.TAdd(ca);
                return RedirectToAction("AdminCategoryList");
            }
            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }
        [HttpGet]
        public ActionResult UpdateCategory(int id)
        {
            Category category = cm.GetByID(id);
            return View(category);
        }
        [HttpPost]
        public ActionResult UpdateCategory(Category a)
        {
            cm.TUpdate(a);
            return RedirectToAction("AdminCategoryList");
        }
        public ActionResult DeleteCategory(int  id)
        {
            cm.CategoryStatusFalseBL(id);
            return RedirectToAction("AdminCategoryList");
        }
        public ActionResult CategoryStatusTrue(int id)
        {
            cm.CategoryStatusTrueBL(id);
            return RedirectToAction("AdminCategoryList");
        }
    }
}

MvcBlog/Controllers/CommentController.cs
using Business.Concrete;
using DataAccessLayer.EntityFramework;
using Entity.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcBlog.Controllers
{
    public class CommentController : Controller
    {
        // GET: Comment
        CommentManager cm = new CommentManager(new EfCommentDal());
        [AllowAnonymous]
        public PartialViewResult CommentList(int id)
        {
            var commentlist = cm.CommentByBlog(id);
            return PartialView(commentlist);
        }
        [AllowAnonymous]
        [HttpGet]
        public PartialViewResult LeaveComment(int id)
        {
            ViewBag.id = id;
            return PartialView();
        }
        [HttpPost]
        [AllowAnonymous]
        public PartialViewResult LeaveComment(Comment c)
        {
            c.CommentStatus = true;
            cm.TAdd(c);
            return PartialView();
        }
      
            public ActionResult AdminCommentListTrue()
        {
            var commentlist = cm.CommentByStatusTrue();
            return View(commentlist);
        }
        public ActionResult AdminCommentListFalse()
        {
            var commentlist = cm.CommentByStatusFalse();
            return View(commentlist);
        }

        public ActionResult UpdateCommentToFalse(int id )
        {
            cm.CommentStatusChangeToFalse(id);
            return RedirectToAction("AdminCommentList");
        }
        public ActionResult UpdateCommentToTrue(int id)
        {
            cm.CommentStatusChangeToFalse(id);
            return RedirectToAction("AdminCommentList");
        }
    }
}

MvcBlog/Views/Blog/AddNewBlog.cshtml
@model Entity.Concrete.Blog
@{
    ViewBag.Title = "AddNewBlog";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Yeni Blog Ekle</h2>
<form class="form-group" method="post">
    @Html.Label("Başlık")
    @Html.TextBoxFor(x => x.BlogTitle, new { @class = "form-control" })
    @Html.Label("Kategori")
    @Html.DropDownListFor(x => x.CategoryId, (List<SelectListItem>)ViewBag.category, new { @class = "form-control" })
    @Html.Label("Tarih")
    @Html.TextBoxFor(x => x.BlogDate, new { @class = "form-control" })
    @Html.Label("Resim")
    @Html.TextBoxFor(x => x.BlogImage, new { @class = "form-control" })
    @Html.Label("Yazar")
    @Html.DropDownListFor(x => x.AuthorId, (List<SelectListItem>)ViewBag.author, new { @class = "form-control" })
    @Html.Label("İçerik")
    @Html.TextAreaFor(x => x.BlogContent, 40, 80, new { @class = "form-control" })
    <br />
    <button class="btn btn-sm- btn-primary">Kaydet</button>
</form>

MvcBlog/Views/Blog/AdminBlogList.cshtml
@model IEnumerable<Entity.Concrete.Blog>
@{
    ViewBag.Title = "AdminBlogList";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Blog Listesi</h2>

<table class="table table-bordered table-sm">
    <tr>
        <th>TARİH</th>
        <th>BAŞLIK</th>
        <th>KATEGORİ</th>
        <th>YAZAR</th>
        <th>İŞLEMLER</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.BlogDate.ToShortDateString() </td>
            <td>@item.BlogTitle </td>
            <td>@item.Category.CategoryName </td>
            <td>@item.Author.AuthorName </td>
            <td>
                <a href="/Blog/Updateblog/@item.BlogId" class="btn btn-secondary btn-sm">Düzenle</a>
                <a href="/Blog/BlogDetails/@item.BlogId" class="btn btn-info btn-sm">Detaylar</a>
                <a href="/Blog/DeleteBlog/@item.BlogId" class="btn btn-danger btn-sm">Sil</a>
                <a href="/Blog/GetCommentByBlog/@item.BlogId" class="btn btn-success btn-sm">Yorumlar</a>
            </td>
        </tr>
    }
</table>
<a href="/Blog/AddNewBlog/" class="btn btn-primary btn-sm">Blog Ekle</a>

MvcBlog/Views/Blog/AuthorBlogList.cshtml
@model IEnumerable<Entity.Concrete.Blog>
@{
    ViewBag.Title = "AuthorBlogList";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>

<html>



<body class="hold-transition sidebar-mini">

    <!-- Main content -->

    <section class="content">

        <!-- Default box -->

        <div class="card">

            <div class="card-header">

                <h3 class="card-title">Blog Listesi</h3>

                <div class="card-tools">

                    <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">

                        <i class="fas fa-minus"></i>

                    </button>

                    <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">

                        <i class="fas fa-times"></i>

                    </button>

                </div>

            </div>

            <div class="card-body p-0">

                <table class="table table-striped projects">

                    <thead>

                        <tr>

                            <th style="width: 1%">

                                ID

                            </th>

                            <th style="width: 20%">

                                BLOG ADI

                            </th>



                            <th style="width: 8%" class="text-center">

                                DURUM

                            </th>

                            <th style="width: 20%">

                            </th>

                        </tr>

                    </thead>

                    <tbody>
                        @foreach (var item in Model)
                        {



                            <tr>

                                <td>

                                    @item.BlogId

                                </td>

                                <td>

                                    @item.BlogTitle
                                </td>




                                <td class="project-state">

                                    <span class="badge badge-success">Success</span>

                                </td>

                                <td class="project-actions text-right">

                                    <a class="btn btn-primary btn-sm" href="#">

                                        <i class="fas fa-folder">

                                        </i>

                                        Yazılar

                                    </a>

                                    <a class="btn btn-info btn-sm" href="#">

                                        <i class="fas fa-pencil-alt">

                                        </i>

                                        Düzenle

                                    </a>

                                    <a class="btn btn-danger btn-sm" href="#">

                                        <i class="fas fa-trash">

                                        </i>

                                        Sil

                                    </a>

                                </td>

                            </tr>
                        }
                    </tbody>

                </table>

            </div>

            <!-- /.card-body -->

        </div>

        <!-- /.card -->

    </section>

</body>

</html>

MvcBlog/Views/Blog/BlogByCategory.cshtml
@model IEnumerable<Entity.Concrete.Blog>  
@{
    ViewBag.Title = "BlogByCategory";
    Layout = "~/Views/Shared/Layout.cshtml";
}


<div class="py-5 bg-light">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
            
                <h3>@ViewBag.categoryname</h3>
                <p>@ViewBag.categorydesc</p>
               
            </div>
        </div>
    </div>
</div>
<div class="site-section bg-white">
    <div class="container">
        <div class="row">
            
            @foreach (var item in Model)
            {
                <div class="col-lg-4 mb-4">

                    <div class="entry2">
                        <a href="/Blog/BlogDetails/@item.BlogId/"><img src="@item.BlogImage" alt="Image"style="height:250px" class="img-fluid rounded"></a>
                        <div class="excerpt">
                            <span class="post-category text-white bg-success mb-3">@item.Category.CategoryName</span>

                            <h2><a href="/Blog/BlogDetails/@item.BlogId/">@item.BlogTitle</a></h2>
                            <div class="post-meta align-items-center text-left clearfix">
                                <figure class="author-figure mb-0 mr-3 float-left"><img src="@item.Author.AuthorImage" alt="Image" class="img-fluid"></figure>
                                <span class="d-inline-block mt-1"><a href="#">@item.Author.AuthorName</a></span>
                                <span>&nbsp;-&nbsp; @item.BlogDate.ToShortDateString()</span>
                            </div>

                            <p>@item.BlogContent.Substring(0,item.BlogContent.Substring(0,200).LastIndexOf(""))...</p>
                            <p><a href="#">Devamını Oku</a></p>
                        </div>
                    </div>
                </div>
            }
        </div>
        
    </div>
</div>
@Html.Action("Footer","About")

MvcBlog/Views/Blog/BlogCover.cshtml
@model IEnumerable<Entity.Concrete.Blog>
@foreach (var item in Model)
{
<div class="site-cover site-cover-sm same-height overlay single-page" style="background-image: url('@item.BlogImage');">
    <div class="container">
        <div class="row same-height justify-content-center">
            <div class="col-md-12 col-lg-10">
                <div class="post-entry text-center">
                    <span class="post-category text-white bg-success mb-3">@item.Category.CategoryName</span>
                    <h1 class="mb-4"><a href="#">@item.BlogTitle</a></h1>
                    <div class="post-meta align-items-center text-center">
                        <figure class="author-figure mb-0 mr-3 d-inline-block"><img src="@item.Author.AuthorImage" alt="Image" class="img-fluid"></figure>
                        <span class="d-inline-block mt-1">@item.Author.AuthorName</span>
                        <span>&nbsp;-&nbsp; @item.BlogDate.ToShortDateString()</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
}

MvcBlog/Views/Blog/BlogDetails.cshtml
@{
    ViewBag.Title = "BlogDetails";
    Layout = "~/Views/Shared/Layout.cshtml";
}

@Html.Action("BlogCover", "Blog")
<section class="site-section py-lg">
    <div class="container">

        <div class="row blog-entries element-animate">

            <div class="col-md-12 col-lg-8 main-content">
                @Html.Action("BlogReadAll", "Blog")
                @Html.Action("CommentList", "Comment")
            </div>
            <div class="col-md-12 col-lg-4 sidebar">
                @Html.Action("AuthorAbout", "Author")
              @Html.Action("AuthorPopularPost", "Author")
                @Html.Action("CategoryList", "Category")
            </div>
        </div>
    </div>
</section>
@*@Html.Action("OtherFeaturedPost", "Blog")*@
@*@Html.Action("AddMail", "SubScribe")*@
@Html.Action("Footer", "About")

MvcBlog/Views/Blog/BlogList.cshtml
@using PagedList
@using PagedList.Mvc

@model IEnumerable<Entity.Concrete.Blog> 
    @{ string color=""; }

<div class="site-section">
    <div class="container">
        <div class="row mb-5">
            <div class="col-12">
                <h2>Post Listesi</h2>
            </div>
        </div>
        <div class="row">
            @foreach (var item in Model)
            {
                if (item.Category.CategoryName=="Yazılım")
                {
                    color = "post-category text-white bg-secondary mb-3";
                }
                if (item.Category.CategoryName == "Teknoloji")
                {
                    color = "post-category text-white bg-info mb-3";
                }
                if (item.Category.CategoryName == "Spor")
                {
                    color = "post-category text-white bg-warning mb-3";
                }
                if (item.Category.CategoryName == "Seyehat")
                {
                    color = "post-category text-white bg-danger mb-3";
                }
            <div class="col-lg-4 mb-4">
                <div class="entry2">
                    <a href="/Blog/BlogDetails/@item.BlogId"><img src="@item.BlogImage"style="height:250px"  alt="Image" class="img-fluid rounded"></a>
                    <div class="excerpt">
                        <span class="@color">@item.Category.CategoryName</span>

                        <h2><a href="/Blog/BlogDetails/@item.BlogId">@item.BlogTitle</a></h2>
                        <div class="post-meta align-items-center text-left clearfix">
                            <figure class="author-figure mb-0 mr-3 float-left"><img src="/miniblog/images/person_1.jpg" alt="Image" class="img-fluid"></figure>
                            <span class="d-inline-block mt-1"> <a href="#">@item.Author.AuthorName</a></span>
                            <span>&nbsp;-&nbsp; @item.BlogDate.ToShortDateString()</span>
                            Puan:@item.BlogRating
                        </div>

                        <p>@item.BlogContent.Substring(0,item.BlogContent.Substring(0,200).LastIndexOf(" "))...</p>
                        <p><a href="/Blog/BlogDetails/@item.BlogId">Devamını Oku</a></p>
                    </div>
                </div>
            </div>
            }
        </div>
         
    </div>
</div>

@Html.PagedListPager((IPagedList)Model,page=>Url.Action("Index",new { page }))

MvcBlog/Views/Blog/BlogReadAll.cshtml
@model IEnumerable<Entity.Concrete.Blog>
@foreach (var item in Model)
{


    <div class="post-content-body">
        <p> @item.BlogContent</p>
        <div class="row mb-5 mt-5">
            <div class="col-md-12 mb-4">
                <img src="@item.BlogImage2" alt="Image placeholder" class="img-fluid rounded">
            </div>
            <div class="col-md-6 mb-4">
                <img src="@item.BlogImage3" alt="Image placeholder" class="img-fluid rounded">
            </div>
            <div class="col-md-6 mb-4">
                <img src="@item.BlogImage4" alt="Image placeholder" class="img-fluid rounded">
            </div>
        </div>
    </div>
}

MvcBlog/Views/Blog/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<br />
@Html.Action("FeaturedPost", "Blog")

@Html.Action("BlogList", "Blog")
@*@Html.Action("OtherFeaturedPost", "Blog")*@
@Html.Action("AddMail", "SubScribe")
@Html.Action("Footer", "About")